In [1]:
import mlflow
import tensorflow as tf
MLFLOW_TRACKING_URI="http://mlflow_server:5000/"
mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
logged_model = 'runs:/2e80a0ba77e3459ea5045879ca29fbec/model'
loaded_model = mlflow.pyfunc.load_model(logged_model)

# print("--")

/usr/local/lib/python3.6/dist-packages/keras/backend.py:401: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.
  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '


In [2]:
import pandas as pd
from os import path 

features=['x','y','pen_up','pressure']
doc_path = "/data/elekin/doc"
metadf=pd.read_csv(path.join(doc_path,"metadata-202106-v1.csv"),index_col=0)
# metadf[metadf["temblor"]=='si']

In [3]:
from scipy.signal import resample

X = []
y = []

for path, level in zip(metadf.abs_path, metadf.level):
    df = pd.read_csv(path, sep="\s+",header=None,names=features,skiprows=1,usecols=[0,1,3,6])
    X.append(resample(df.values.astype('int16'), 4096))
    y.append(level)

In [4]:
import numpy as np
predictions=loaded_model.predict(np.array(X))
predictions

array([[9.99947190e-01, 4.30034597e-05, 9.71540339e-06],
       [7.62586296e-01, 1.13812961e-01, 1.23600766e-01],
       [9.99987125e-01, 1.06533817e-05, 2.31639683e-06],
       [7.62594879e-01, 1.13810599e-01, 1.23594545e-01],
       [9.99789298e-01, 2.01125891e-04, 9.51214224e-06],
       [7.62586296e-01, 1.13812961e-01, 1.23600766e-01],
       [9.99983907e-01, 1.34207203e-05, 2.62362664e-06],
       [7.62586296e-01, 1.13812961e-01, 1.23600766e-01],
       [9.99836922e-01, 1.55274640e-04, 7.75040007e-06],
       [7.62586296e-01, 1.13812961e-01, 1.23600766e-01],
       [9.99725997e-01, 2.34724532e-04, 3.92453767e-05],
       [7.62586296e-01, 1.13812961e-01, 1.23600766e-01],
       [9.99830723e-01, 1.61030810e-04, 8.25720508e-06],
       [9.34637606e-01, 3.54437642e-02, 2.99185999e-02],
       [9.59908068e-01, 2.65743602e-02, 1.35175362e-02],
       [1.74535526e-05, 1.35801147e-05, 9.99969006e-01],
       [9.99818146e-01, 1.31224588e-04, 5.06718352e-05],
       [9.80721414e-02, 8.85898

In [5]:
tf.one_hot(tf.argmax(predictions, axis=1), depth=3)

<tf.Tensor: shape=(53, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
      

In [6]:
data=tf.data.experimental.load("gs://mlflow-arts/mlflow_artifacts/2/df4c6d7d2bbb4bb8a9861370536f7788/artifacts/ethw_tf_test_dir")

In [7]:
for feat, label in data:
    print(label)

tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([0. 1. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 1.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)


In [8]:
predictions = loaded_model.predict(data.batch(1).prefetch(5).cache())

In [9]:
tf.one_hot(tf.argmax(predictions, axis=1), depth=3)

<tf.Tensor: shape=(18, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)>

In [10]:
dataset = tf.data.Dataset.from_tensor_slices((X, tf.one_hot(y, 3)))
for feat,labels in dataset.take(2):
    print(labels)
tf.data.experimental.save(dataset, "/test", compression="GZIP")

tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)


In [11]:
tf.data.experimental.load("/test", compression="GZIP")

<_LoadDataset shapes: ((4096, 4), (3,)), types: (tf.float64, tf.float32)>